# Generated by Django 4.0.6 on 2022-07-15 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=500)),
                ('preco', models.FloatField()),
                ('ano_lancamento', models.IntegerField()),
                ('data_inclusao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
